spring.application.name=movieFlix


spring.datasource.url=jdbc:postgresql://localhost:5432/flix
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true

flix.security.secret=19829829081082018208012